#server details
server:
  port: 8181
  
# database details

spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: system
    password: Oracle
    
#JPA details 
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create